### ISSUE TITLE
TODO: Identity

### ISSUE THREAD

**Issue by YanicHoegger** [YanicHoegger/TravelTracker#3]
- [x] AccountController only accessable when logged in
- [ ] Email verification
- [x] Feedback when not correctly logged in
- [x] Show username when logged in

Helping links:
http://www.blinkingcaret.com/2016/11/30/asp-net-identity-core-from-scratch/
https://medium.com/@goodealsnow/asp-net-core-identity-3-0-6018fc151b4

**Comment by YanicHoegger** [comment]
All done beside Email verification --> Will be done in next stage
